// Generated by CoffeeScript 1.6.3
(function() {
  var ConvertPreprocessor, exec, fs, nodecr, tmp, util;

  nodecr = require('nodecr');

  util = require('util');

  tmp = require('tmp');

  exec = require('child_process').exec;

  fs = require('fs');

  nodecr.process("" + __dirname + "/test.jpg", function(err, text) {
    console.log(util.inspect(err));
    return console.log(util.inspect(text));
  }, null, null, null, ConvertPreprocessor = function(inputFile, next) {
    console.log("node-tesseract: preprocessor: convert: Processing '" + inputFile + "'");
    tmp.tmpName({
      postfix: '.tif'
    }, function(err, outputFile) {
      var command;
      if (err) {
        next(err, null);
        return;
      }
      command = ['convert', '-colorspace', 'gray', '-sharpen', '10', '-threshold', '50%', '-colors', '32', '-normalize', inputFile, outputFile].join(' ');
      console.log("node-tesseract: preprocessor: convert: Running '" + command + "'");
      exec(command, function(err, stdout, stderr) {
        var cleanup;
        if (err) {
          next(err, null);
        } else {
          cleanup = function() {
            console.log("node-tesseract: preprocessor: convert: Deleting '" + outputFile + "'");
            fs.unlink(outputFile, function(err) {});
          };
          next(null, outputFile, cleanup);
        }
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
