// Generated by CoffeeScript 1.6.3
/**
 * isAuthenticated
 *
 * @module      :: Policy
 * @description :: Simple policy to allow any authenticated user
 *                 Assumes that your login action in one of your controllers sets `req.session.authenticated = true;`
 * @docs        :: http://sailsjs.org/#!documentation/policies
*
*/


(function() {
  module.exports = function(req, res, ok) {
    console.log(req.session.authenticated);
    if (req.session.authenticated) {
      return ok();
    }
    if (req.action === 'signin' && req.controller === 'session') {
      return ok();
    }
    req.session.flash = [
      {
        name: 'loginForced',
        message: 'Bitte anmelden!'
      }
    ];
    return res.redirect('/session/signin');
  };

}).call(this);

/*
//@ sourceMappingURL=isAuthenticated.map
*/
