// Generated by CoffeeScript 1.6.3
/**
* User
*
* @module      :: Model
* @description :: A short summary of how this model works and what it represents.
* @docs		:: http://sailsjs.org/#!documentation/models
*/


(function() {
  module.exports = {
    schema: true,
    attributes: {
      name: {
        type: 'string',
        required: true
      },
      email: {
        type: 'string',
        required: true,
        email: true,
        unique: true
      },
      encryptedPassword: {
        type: 'string'
      },
      toJSON: function() {
        var obj;
        obj = this.toObject();
        delete obj.password;
        delete obj.confirmation;
        delete obj.encryptedPassword;
        delete obj._csrf;
        return obj;
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=User.map
*/
